<div class="h-full min-h-0 flex flex-col">
    <div class="flex-1 min-h-0 overflow-y-auto no-scrollbar">
        <div class="max-w-3xl mx-auto pb-6">
            <div class="bg-panel border border-border rounded-xl overflow-hidden">
                @php
                    $ready = $isUserHaveActiveModel && $isUserHaveChats;
                    $headSubtitle = $ready
                        ? 'Generated by your active AI model · <span class="text-them">'.($isActive ? 'Active' : 'Paused').'</span>'
                        : 'Requires an active AI model and at least one chat.';
                @endphp
                <x-form-head :title="$scheduledMessage ? 'Edit scheduled message' : 'Schedule a message'"
                             :subtitle="$headSubtitle"
                             :status="$ready ? 'ready' : 'blocked'"
                             :status-class="$ready ? 'border-them/50 text-them bg-them/10' : 'border-you/30 text-you bg-you/10'"/>

                <x-flash-message variant="error" class="mb-6 mx-6 mt-6" :timeout="null"/>

                @if($ready)
                    <form wire:submit.prevent="submit">
                        <div class="px-4 sm:px-6 py-5 grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-0">

                            <x-section-divider title="Message"/>

                            <x-form-field label="topic" name="topic" class="col-span-full">
                                <x-form-input wire:model="topic" placeholder="e.g. Weekly digest"/>
                            </x-form-field>

                            <x-form-field label="description" name="description" class="col-span-full">
                                <x-form-textarea wire:model="description" rows="4" placeholder="e.g. Write a short update about my week, highlighting what I accomplished..."/>
                            </x-form-field>

                            <x-toggle-row title="Active" description="Message will be delivered on schedule." class="col-span-full mb-5">
                                <x-toggle :active="$isActive" wire:click="$toggle('isActive')"/>
                            </x-toggle-row>

                            <x-section-divider title="Schedule"/>

                            <x-form-field label="schedule_type" name="scheduledType">
                                <x-form-select wire:model.live="scheduledType">
                                    <option value="recurring" class="bg-panel">Recurring</option>
                                    <option value="specific_dates" class="bg-panel">Specific Dates</option>
                                </x-form-select>
                            </x-form-field>

                            <x-form-field label="run_at" name="runAt">
                                <x-form-input type="time" wire:model="runAt"/>
                            </x-form-field>

                            @if($scheduledType === 'recurring')
                                <x-form-field label="starts_on" name="startDate">
                                    <x-form-input type="date" wire:model.live="startDate"/>
                                </x-form-field>
                            @endif

                            @if($scheduledType === 'recurring')
                                <x-form-field label="frequency" name="frequency" class="col-span-full">
                                    <x-form-select wire:model.live="frequency">
                                        @foreach($frequencies as $value => $label)
                                            <option value="{{ $value }}" class="bg-panel">{{ $label }}</option>
                                        @endforeach
                                    </x-form-select>
                                </x-form-field>

                                @if($frequency === 'weekly')
                                    <x-schedule-summary>Weekly on <span class="text-them">{{ $this->startWeekdayLabel() }}</span></x-schedule-summary>
                                @elseif($frequency === 'monthly')
                                    <x-schedule-summary>Monthly on the <span class="text-them">{{ $this->startMonthlyLabel() }}</span></x-schedule-summary>
                                @elseif($frequency === 'yearly')
                                    <x-schedule-summary>Annually on <span class="text-them">{{ $this->startYearlyLabel() }}</span></x-schedule-summary>
                                @endif

                                <x-form-field label="ends" name="endsType" class="col-span-full">
                                    <x-form-select wire:model.live="endsType">
                                        <option value="never" class="bg-panel">Never</option>
                                        <option value="on_date" class="bg-panel">On date</option>
                                    </x-form-select>

                                    @if($endsType === 'on_date')
                                        <x-form-input type="date" wire:model="endsOn" class="mt-2"/>
                                        <x-form-error name="endsOn"/>
                                    @endif
                                </x-form-field>
                            @else
                                <x-form-field label="run_dates" name="runDates" class="col-span-full">
                                    <div class="space-y-2">
                                        @foreach($runDates as $index => $date)
                                            <div class="flex items-center gap-2">
                                                <x-form-input type="date" wire:model="runDates.{{ $index }}" class="flex-1"/>
                                                <button type="button" wire:click="removeRunDate({{ $index }})"
                                                        class="px-3 py-2 rounded-md text-[11px] font-mono text-ink-muted hover:text-danger hover:border-danger/40 border border-transparent transition-all cursor-pointer">
                                                    remove
                                                </button>
                                            </div>
                                        @endforeach
                                    </div>
                                    <button type="button" wire:click="addRunDate"
                                            class="mt-2 px-3 py-2 rounded-md text-xs font-mono text-them border border-them/40 hover:bg-them/10 transition-all cursor-pointer">
                                        + Add date
                                    </button>
                                </x-form-field>
                            @endif

                            <x-section-divider title="Delivery"/>

                            <x-form-field label="chats" name="selectedChats" class="col-span-full">
                                @if($chats->isNotEmpty())
                                    <div class="max-h-48 overflow-y-auto no-scrollbar border border-border rounded-md bg-[var(--color-panel)]">
                                        @foreach($chats as $chat)
                                            <label class="flex items-center justify-between bg-[var(--color-panel)] border-b border-border/60 px-4 py-3 cursor-pointer last:border-b-0 hover:bg-[var(--color-them)]/5 transition-colors">
                                                <span class="text-[12.5px] text-ink font-mono">{{ $chat['name'] }}</span>
                                                <input type="checkbox" value="{{ $chat['id'] }}" wire:model="selectedChats"
                                                       class="w-4 h-4 cursor-pointer accent-[var(--color-them)]">
                                            </label>
                                        @endforeach
                                    </div>
                                @else
                                    <p class="text-[11px] text-ink-muted font-mono">You don't have any chats yet. Start a conversation to select it here.</p>
                                @endif
                            </x-form-field>

                            @if($isMultiLanguageEnabled)
                                <x-section-divider title="Language"/>

                                <x-form-field name="languages" class="col-span-full">
                                    <div class="flex items-center justify-between mb-1.5">
                                        <label class="block text-xs text-ink-muted font-mono"><span class="text-ink-muted">$</span> languages</label>
                                        <span class="text-[10.5px] font-mono text-ink-muted">select up to {{ $maxLanguages }} · <span class="text-them">{{ count($languages) }}/{{ $maxLanguages }}</span></span>
                                    </div>
                                    <div class="max-h-48 overflow-y-auto no-scrollbar border border-border rounded-md bg-[var(--color-panel)]">
                                        <div class="grid grid-cols-2 gap-x-4 gap-y-1 p-3">
                                            @foreach($availableLanguages as $language)
                                                <label class="flex items-center gap-2.5 rounded-md px-2.5 py-1.5 cursor-pointer hover:bg-them/10 transition-colors">
                                                    <input type="checkbox" value="{{ $language }}" wire:model="languages"
                                                           class="w-4 h-4 cursor-pointer accent-[var(--color-them)]">
                                                    <span class="text-[12.5px] text-ink font-mono truncate">{{ $language }}</span>
                                                </label>
                                            @endforeach
                                        </div>
                                    </div>
                                </x-form-field>
                            @else
                                <x-toggle-row title="Multi-language"
                                              description="Your active model doesn't support multi-language. Enable it on the model to schedule messages in multiple languages."
                                              class="col-span-full mb-5">
                                    <x-badge class="border-border text-ink-muted">unavailable</x-badge>
                                </x-toggle-row>
                            @endif
                        </div>

                        <x-form-footer cancel-action="$dispatch('set-page', 'list_scheduled_messages')">
                            <x-submit-button>{{ $scheduledMessage ? 'Save changes' : 'Run ./schedule-message' }}</x-submit-button>
                        </x-form-footer>
                    </form>
                @elseif(!$isUserHaveActiveModel)
                    <x-empty-state title="No active AI model"
                                   description="You need an active and available AI model to generate scheduled messages. Add one from the AI models page."
                                   description-class="text-[11px] mt-1.5 max-w-sm mx-auto leading-relaxed">
                        <x-slot:action>
                            <x-submit-button type="button">Go to AI models</x-submit-button>
                        </x-slot:action>
                    </x-empty-state>
                @else
                    <x-empty-state title="No chats yet"
                                   description="You need at least one chat to deliver a scheduled message. Start a conversation first, then come back here."
                                   description-class="text-[11px] mt-1.5 max-w-sm mx-auto leading-relaxed"/>
                @endif
            </div>
        </div>
    </div>
</div>
